<a href="https://colab.research.google.com/github/KJOELJOYSON2427/Linear_Regression_Model/blob/main/linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
from abc import abstractclassmethod
class Linear_Regression():
  @abstractclassmethod
  def __init__(self):
    pass

  @abstractclassmethod
  def fit(self):
    pass
  @abstractclassmethod
  def update_weights(self):
    pass
  @abstractclassmethod
  def predict(self):
    pass

In [7]:
class LinearRegression(Linear_Regression):
    def __init__(self, learning_rate=0.01, n_iterations=1000):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        # Initialize weights and bias
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        # Gradient Descent
        for _ in range(self.n_iterations):
            # Approximate y with linear combination of weights and x, plus bias
            y_predicted = self.predict(X)

            # Compute gradients
            dw = (1/n_samples) * np.dot(X.T, (y_predicted - y))
            db = (1/n_samples) * np.sum(y_predicted - y)

            # Update weights and bias
            self.update_weights(dw, db)

    def update_weights(self, dw, db):
        # Update weights and bias using gradients and learning rate
        self.weights -= self.learning_rate * dw
        self.bias -= self.learning_rate * db

    def predict(self, X):
        # Calculate predictions
        y_predicted = np.dot(X, self.weights) + self.bias
        print(y_predicted)
        return y_predicted



# Linear Regression Implementation

This notebook contains a Python implementation of Linear Regression using gradient descent.

## Class: `Linear_Regression` (Abstract Base Class)
This class serves as an abstract base class defining the required methods for a linear regression model:
- `__init__()`: Constructor
- `fit()`: Method for training the model
- `update_weights()`: Method for updating model weights
- `predict()`: Method for making predictions

## Class: `LinearRegression`
This class inherits from `Linear_Regression` and provides a concrete implementation of the linear regression algorithm using gradient descent.

### Parameters:
- `learning_rate`: The step size for updating weights during gradient descent.
- `n_iterations`: The number of iterations for the gradient descent algorithm.

### Methods:
- `__init__(self, learning_rate=0.01, n_iterations=1000)`: Initializes the learning rate, number of iterations, and sets initial weights and bias to None.
- `fit(self, X, y)`: Trains the model using the provided input features `X` and target variable `y`. It initializes weights and bias, then iteratively updates them using gradient descent for a specified number of iterations.
- `update_weights(self, dw, db)`: Updates the model's weights and bias based on the calculated gradients (`dw` and `db`) and the learning rate.
- `predict(self, X)`: Predicts the output for the given input features `X` using the learned weights and bias.

## Gradient Descent Details:
The `fit` method uses gradient descent to minimize the mean squared error. The gradients for the weights (`dw`) and bias (`db`) are calculated as follows:

$dw = \frac{1}{n\_samples} \cdot X^T \cdot (y\_{predicted} - y)$

$db = \frac{1}{n\_samples} \cdot \sum (y\_{predicted} - y)$

Where:
- $n\_samples$ is the number of training samples.
- $X$ is the input feature matrix.
- $X^T$ is the transpose of the input feature matrix.
- $y\_{predicted}$ is the vector of predicted outputs.
- $y$ is the vector of actual outputs.

The weights and bias are updated in each iteration using the following rules:

$weights = weights - learning\_rate \cdot dw$

$bias = bias - learning\_rate \cdot db$

In [6]:
import numpy as np

# Sample data
X = np.array([[1, 2],
              [3, 4],
              [5, 6]]) # 3 samples, 2 features

y = np.array([7, 8, 9]) # Actual outputs

# Example predicted outputs (could be from an initial guess or previous iteration)
y_predicted = np.array([6.5, 8.2, 9.8])

# Calculate the error
error = y_predicted - y

# Calculate the dot product of X.T and the error
dot_product_result = np.dot(X.T, error)

print("X (input features):\n", X)
print("\nX.T (transpose of X):\n", X.T)
print("\ny (actual outputs):\n", y)
print("\ny_predicted (predicted outputs):\n", y_predicted)
print("\nerror (y_predicted - y):\n", error)
print("\nnp.dot(X.T, error) (dot product of X.T and error):\n", dot_product_result)

X (input features):
 [[1 2]
 [3 4]
 [5 6]]

X.T (transpose of X):
 [[1 3 5]
 [2 4 6]]

y (actual outputs):
 [7 8 9]

y_predicted (predicted outputs):
 [6.5 8.2 9.8]

error (y_predicted - y):
 [-0.5  0.2  0.8]

np.dot(X.T, error) (dot product of X.T and error):
 [4.1 4.6]
